version:  '3.8'
services:
  datascience-notebook:
    image: jupyter/base-notebook
    volumes:
      - jupyter_data:/home/docker_worker/work            
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: >
      start-notebook.sh  --NotebookApp.token=<TOKEN_VALUE_64_HASHCODE>
      --NotebookApp.open_browser=False
      --NotebookApp.password=usha1:<PASSWORD_SHA>
      --NotebookApp.ip=*"
    user: root
    environment:
      NB_USER: docker_worker
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
volumes:
    jupyter_data: {}